# Site settings
title: UQ Computing Society
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://uqcs.org.au" # the base hostname & protocol for your site
twitter_username: uqcomputing 
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
exclude: [vendor]
